// <auto-generated />
namespace MISA.WDT03.BTAnh.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Alo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Alo));
        
        string IMigrationMetadata.Id
        {
            get { return "201908160427265_Alo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
