// <auto-generated />
namespace MISA.WDT03.BTAnh
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Intial3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Intial3));
        
        string IMigrationMetadata.Id
        {
            get { return "201908201722197_Intial3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
